import '@/styles/globals.css'
import '@ant-design/v5-patch-for-react-19'

import { AntdRegistry } from '@ant-design/nextjs-registry'
import type { Metadata } from 'next'
import { Geist } from 'next/font/google'
import { AntdWrapper } from '@/app/components/antd-wrapper'
import { TRPCReactProvider } from '@/trpc/react'

export const metadata: Metadata = {
  title: 'Create T3 App',
  description: 'Generated by create-t3-app',
  icons: [{ rel: 'icon', url: '/favicon.ico' }],
}

const geist = Geist({
  subsets: ['latin'],
  variable: '--font-geist-sans',
})

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html
      lang='en'
      className={`${geist.variable}`}
    >
      <body>
        <TRPCReactProvider>
          <AntdRegistry>
            <AntdWrapper>{children}</AntdWrapper>
          </AntdRegistry>
        </TRPCReactProvider>
      </body>
    </html>
  )
}
